### ISSUE TITLE
Using Oculus/Iris-likes for shaders causes guns to not render (bug/potential fix)

### ISSUE THREAD

**Issue by jamioflan** [FlansMods/FlansModReloaded#44]
Iris and all iris-likes replace/disable all non-vanilla core shaders when iris shaderpacks are active - i noticed your flansmod gun shaders arent too different to the vanilla entity shaders, if possible, use those - they might require a little extra data (i.e overlay coords and light), but its a menial performance impact

**Comment by MatchTerm** [comment]
Bump, would really like Oculus comp
