### ISSUE TITLE
Improvement: gun related player attributes

### ISSUE THREAD

**Issue by Ikxale** [FlansMods/FlansModReloaded#50]
having an attribute system for some simple things such as gun specific damage and critical chance attributes would be wonderful. 

I'm trying to put together an rpg-esque modpack and i've noticed there is no gun mod available which adds such a thing.

**Comment by jamioflan** [comment]
I've added some attributes 
"flansmod.impact_damage_multiplier"
"flansmod.splash_radius_multiplier"
"flansmod.time_between_shots_multiplier"
"flansmod.shot_spread_multiplier"
"flansmod.vertical_recoil_multiplier"
"flansmod.horizontal_recoil_multiplier"

Could you test that they work?
