### ISSUE TITLE
Issue with mining blocks introduced by this mod in Survival

### ISSUE THREAD

**Issue by archonxgames** [FlansMods/FlansModReloaded#52]
MC Version: 1.20.1
Flan's Mod Reloaded Version: 0.2.147
Issue/s:
- Blocks introduced by the mod such as the gun modification table do not endorse a tool to mine them (The Jade mod usually indicates if a specific block should be mined by a specific tool, and I have noticed that the blocks from this mod do not have any tools assigned to mine them)
- The blocks take a long time to mine (by virtue of first issue)
- The blocks do not drop any item when mined (possibly due to the first issue, its like trying to break stone with your fists or with an axe)

**Comment by jamioflan** [comment]
With current code, the Gun Modification Table is the only mod block that has these issues, and it did indeed not have the mineable/pickaxe tag applied. Pushing a fix now
